#ifndef CNOID_SYSTEMTRAYPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_SYSTEMTRAYPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_SYSTEMTRAYPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_SYSTEMTRAYPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_SYSTEMTRAYPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_SYSTEMTRAYPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_SYSTEMTRAYPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_SYSTEMTRAYPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_SYSTEMTRAYPLUGIN_DLLIMPORT
#   define CNOID_SYSTEMTRAYPLUGIN_DLLEXPORT
#   define CNOID_SYSTEMTRAYPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_SYSTEMTRAYPLUGIN_STATIC
#  define CNOID_SYSTEMTRAYPLUGIN_DLLAPI
#  define CNOID_SYSTEMTRAYPLUGIN_LOCAL
# else
#  ifdef CnoidSystemTrayPlugin_EXPORTS
#   define CNOID_SYSTEMTRAYPLUGIN_DLLAPI CNOID_SYSTEMTRAYPLUGIN_DLLEXPORT
#  else
#   define CNOID_SYSTEMTRAYPLUGIN_DLLAPI CNOID_SYSTEMTRAYPLUGIN_DLLIMPORT
#  endif
#  define CNOID_SYSTEMTRAYPLUGIN_LOCAL CNOID_SYSTEMTRAYPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_SYSTEMTRAYPLUGIN_DLLAPI