#ifndef CNOID_MOTIONCAPTUREPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_MOTIONCAPTUREPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_MOTIONCAPTUREPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_MOTIONCAPTUREPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_MOTIONCAPTUREPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLIMPORT
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLEXPORT
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_MOTIONCAPTUREPLUGIN_STATIC
#  define CNOID_MOTIONCAPTUREPLUGIN_DLLAPI
#  define CNOID_MOTIONCAPTUREPLUGIN_LOCAL
# else
#  ifdef CnoidMotionCapturePlugin_EXPORTS
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLAPI CNOID_MOTIONCAPTUREPLUGIN_DLLEXPORT
#  else
#   define CNOID_MOTIONCAPTUREPLUGIN_DLLAPI CNOID_MOTIONCAPTUREPLUGIN_DLLIMPORT
#  endif
#  define CNOID_MOTIONCAPTUREPLUGIN_LOCAL CNOID_MOTIONCAPTUREPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_MOTIONCAPTUREPLUGIN_DLLAPI
