#ifndef CNOID_GOOGLEPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_GOOGLEPLUGIN_EXPORTDECL_H_INCLUDED
# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_GOOGLEPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_GOOGLEPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_GOOGLEPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_GOOGLEPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_GOOGLEPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_GOOGLEPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_GOOGLEPLUGIN_DLLIMPORT
#   define CNOID_GOOGLEPLUGIN_DLLEXPORT
#   define CNOID_GOOGLEPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_GOOGLEPLUGIN_STATIC
#  define CNOID_GOOGLEPLUGIN_DLLAPI
#  define CNOID_GOOGLEPLUGIN_LOCAL
# else
#  ifdef CnoidGooglePlugin_EXPORTS
#   define CNOID_GOOGLEPLUGIN_DLLAPI CNOID_GOOGLEPLUGIN_DLLEXPORT
#  else
#   define CNOID_GOOGLEPLUGIN_DLLAPI CNOID_GOOGLEPLUGIN_DLLIMPORT
#  endif
#  define CNOID_GOOGLEPLUGIN_LOCAL CNOID_GOOGLEPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_GOOGLEPLUGIN_DLLAPI