#ifndef CNOID_FILEEXPLORERPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_FILEEXPLORERPLUGIN_EXPORTDECL_H_INCLUDED
# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_FILEEXPLORERPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_FILEEXPLORERPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_FILEEXPLORERPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_FILEEXPLORERPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_FILEEXPLORERPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_FILEEXPLORERPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_FILEEXPLORERPLUGIN_DLLIMPORT
#   define CNOID_FILEEXPLORERPLUGIN_DLLEXPORT
#   define CNOID_FILEEXPLORERPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_FILEEXPLORERPLUGIN_STATIC
#  define CNOID_FILEEXPLORERPLUGIN_DLLAPI
#  define CNOID_FILEEXPLORERPLUGIN_LOCAL
# else
#  ifdef CnoidFileExplorerPlugin_EXPORTS
#   define CNOID_FILEEXPLORERPLUGIN_DLLAPI CNOID_FILEEXPLORERPLUGIN_DLLEXPORT
#  else
#   define CNOID_FILEEXPLORERPLUGIN_DLLAPI CNOID_FILEEXPLORERPLUGIN_DLLIMPORT
#  endif
#  define CNOID_FILEEXPLORERPLUGIN_LOCAL CNOID_FILEEXPLORERPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_FILEEXPLORERPLUGIN_DLLAPI