#ifndef CNOID_COLLISIONSEQPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_COLLISIONSEQPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_COLLISIONSEQPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_COLLISIONSEQPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_COLLISIONSEQPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_COLLISIONSEQPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_COLLISIONSEQPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_COLLISIONSEQPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_COLLISIONSEQPLUGIN_DLLIMPORT
#   define CNOID_COLLISIONSEQPLUGIN_DLLEXPORT
#   define CNOID_COLLISIONSEQPLUGIN_DLLLOCAL
#  endif
# endif

#ifdef CnoidCollisionSeqPlugin_EXPORTS
#   define CNOID_COLLISIONSEQPLUGIN_DLLAPI CNOID_COLLISIONSEQPLUGIN_DLLEXPORT
#else
#   define CNOID_COLLISIONSEQPLUGIN_DLLAPI CNOID_COLLISIONSEQPLUGIN_DLLIMPORT
#endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_COLLISIONSEQPLUGIN_DLLAPI