#ifndef CNOID_BODYEDITPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_BODYEDITPLUGIN_EXPORTDECL_H_INCLUDED
# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_BODYEDITPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_BODYEDITPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_BODYEDITPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_BODYEDITPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_BODYEDITPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_BODYEDITPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_BODYEDITPLUGIN_DLLIMPORT
#   define CNOID_BODYEDITPLUGIN_DLLEXPORT
#   define CNOID_BODYEDITPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_BODYEDITPLUGIN_STATIC
#  define CNOID_BODYEDITPLUGIN_DLLAPI
#  define CNOID_BODYEDITPLUGIN_LOCAL
# else
#  ifdef CnoidBodyEditPlugin_EXPORTS
#   define CNOID_BODYEDITPLUGIN_DLLAPI CNOID_BODYEDITPLUGIN_DLLEXPORT
#  else
#   define CNOID_BODYEDITPLUGIN_DLLAPI CNOID_BODYEDITPLUGIN_DLLIMPORT
#  endif
#  define CNOID_BODYEDITPLUGIN_LOCAL CNOID_BODYEDITPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_BODYEDITPLUGIN_DLLAPI