#ifndef CNOID_VISUALEFFECTPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_VISUALEFFECTPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_VISUALEFFECTPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_VISUALEFFECTPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_VISUALEFFECTPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_VISUALEFFECTPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_VISUALEFFECTPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_VISUALEFFECTPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_VISUALEFFECTPLUGIN_DLLIMPORT
#   define CNOID_VISUALEFFECTPLUGIN_DLLEXPORT
#   define CNOID_VISUALEFFECTPLUGIN_DLLLOCAL
#  endif
# endif

#ifdef CnoidVisualEffectPlugin_EXPORTS
#   define CNOID_VISUALEFFECTPLUGIN_DLLAPI CNOID_VISUALEFFECTPLUGIN_DLLEXPORT
#else
#   define CNOID_VISUALEFFECTPLUGIN_DLLAPI CNOID_VISUALEFFECTPLUGIN_DLLIMPORT
#endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_VISUALEFFECTPLUGIN_DLLAPI