#ifndef CNOID_KIOSKPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_KIOSKPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_KIOSKPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_KIOSKPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_KIOSKPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_KIOSKPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_KIOSKPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_KIOSKPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_KIOSKPLUGIN_DLLIMPORT
#   define CNOID_KIOSKPLUGIN_DLLEXPORT
#   define CNOID_KIOSKPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_KIOSKPLUGIN_STATIC
#  define CNOID_KIOSKPLUGIN_DLLAPI
#  define CNOID_KIOSKPLUGIN_LOCAL
# else
#  ifdef CnoidKIOSKPlugin_EXPORTS
#   define CNOID_KIOSKPLUGIN_DLLAPI CNOID_KIOSKPLUGIN_DLLEXPORT
#  else
#   define CNOID_KIOSKPLUGIN_DLLAPI CNOID_KIOSKPLUGIN_DLLIMPORT
#  endif
#  define CNOID_KIOSKPLUGIN_LOCAL CNOID_KIOSKPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_KIOSKPLUGIN_DLLAPI