#ifndef CNOID_SIMPLECOLLIDERPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_SIMPLECOLLIDERPLUGIN_EXPORTDECL_H_INCLUDED

# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_SIMPLECOLLIDERPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_SIMPLECOLLIDERPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_SIMPLECOLLIDERPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLIMPORT
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLEXPORT
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLLOCAL
#  endif
# endif

#ifdef CnoidSimpleColliderPlugin_EXPORTS
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLAPI CNOID_SIMPLECOLLIDERPLUGIN_DLLEXPORT
#else
#   define CNOID_SIMPLECOLLIDERPLUGIN_DLLAPI CNOID_SIMPLECOLLIDERPLUGIN_DLLIMPORT
#endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_SIMPLECOLLIDERPLUGIN_DLLAPI
