#ifndef CNOID_BODYCREATORPLUGIN_EXPORTDECL_H_INCLUDED
# define CNOID_BODYCREATORPLUGIN_EXPORTDECL_H_INCLUDED
# if defined _WIN32 || defined __CYGWIN__
#  define CNOID_BODYCREATORPLUGIN_DLLIMPORT __declspec(dllimport)
#  define CNOID_BODYCREATORPLUGIN_DLLEXPORT __declspec(dllexport)
#  define CNOID_BODYCREATORPLUGIN_DLLLOCAL
# else
#  if __GNUC__ >= 4
#   define CNOID_BODYCREATORPLUGIN_DLLIMPORT __attribute__ ((visibility("default")))
#   define CNOID_BODYCREATORPLUGIN_DLLEXPORT __attribute__ ((visibility("default")))
#   define CNOID_BODYCREATORPLUGIN_DLLLOCAL  __attribute__ ((visibility("hidden")))
#  else
#   define CNOID_BODYCREATORPLUGIN_DLLIMPORT
#   define CNOID_BODYCREATORPLUGIN_DLLEXPORT
#   define CNOID_BODYCREATORPLUGIN_DLLLOCAL
#  endif
# endif

# ifdef CNOID_BODYCREATORPLUGIN_STATIC
#  define CNOID_BODYCREATORPLUGIN_DLLAPI
#  define CNOID_BODYCREATORPLUGIN_LOCAL
# else
#  ifdef CnoidBodyCreatorPlugin_EXPORTS
#   define CNOID_BODYCREATORPLUGIN_DLLAPI CNOID_BODYCREATORPLUGIN_DLLEXPORT
#  else
#   define CNOID_BODYCREATORPLUGIN_DLLAPI CNOID_BODYCREATORPLUGIN_DLLIMPORT
#  endif
#  define CNOID_BODYCREATORPLUGIN_LOCAL CNOID_BODYCREATORPLUGIN_DLLLOCAL
# endif

#endif

#ifdef CNOID_EXPORT
# undef CNOID_EXPORT
#endif
#define CNOID_EXPORT CNOID_BODYCREATORPLUGIN_DLLAPI